## Challenge Numpy : Modéliser la performance d'un marathonien à l'aide d'une régression

In [87]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

df = pd.read_csv(r'ressources/marathon.txt', delimiter="\t", names=["City", "Year", "Time","Seconds"])

**Ajout des colonnes isParis et isBerlin au dataframe**

In [81]:
isParis =[]
isBerlin = []
for City in df['City'] :
    if City == "PARIS" :
        isParis.append(1)
        isBerlin.append(0)
    elif City == "BERLIN" :
        isParis.append(0)
        isBerlin.append(1)
    else :
        isParis.append(0)
        isBerlin.append(0)

df['isParis'] = isParis
df['isBerlin'] = isBerlin

df.head(5)


City  Year      Time  Seconds  isParis  isBerlin
0  PARIS  2011  02:06:29     7589        1         0
1  PARIS  2010  02:06:41     7601        1         0
2  PARIS  2009  02:05:47     7547        1         0
3  PARIS  2008  02:06:40     7600        1         0
4  PARIS  2007  02:07:17     7637        1         0

**On essaie de trouver A dans l équation suivante Y = XA**

In [82]:
#Y = XA
#A* = (X'X)^-1 X'Y
X=[]
Y=[]

for i in df.index:
    inY = [df['Seconds'][i]]
    Y.append(inY)
    inX = [ df['Year'][i],df['isParis'][i],df['isBerlin'][i] ]
    X.append(inX)
    
X = np.matrix(X)

Y = np.matrix(Y)

X


matrix([[2011,    1,    0],
        [2010,    1,    0],
        [2009,    1,    0],
        ...,
        [2008,    0,    0],
        [2009,    0,    0],
        [2010,    0,    0]], dtype=int64)

In [83]:
Y

matrix([[ 7589],
        [ 7601],
        [ 7547],
        [ 7600],
        [ 7637],
        [ 7683],
        [ 7682],
        [ 7736],
        [ 7593],
        [ 7698],
        [ 7780],
        [ 7729],
        [ 7690],
        [ 7777],
        [ 7814],
        [ 7938],
        [ 7806],
        [ 7856],
        [ 7846],
        [ 7803],
        [ 7990],
        [ 7983],
        [ 8033],
        [ 7869],
        [ 7964],
        [ 7849],
        [ 7918],
        [ 7958],
        [ 8047],
        [ 7904],
        [ 8750],
        [ 8333],
        [ 9295],
        [ 9041],
        [ 8457],
        [ 7418],
        [ 7508],
        [ 7568],
        [ 7439],
        [ 7466],
        [ 7556],
        [ 7661],
        [ 7604],
        [ 7495],
        [ 7607],
        [ 7727],
        [ 7662],
        [ 7604],
        [ 7565],
        [ 7661],
        [ 7755],
        [ 7622],
        [ 7711],
        [ 7857],
        [ 7687],
        [ 7857],
        [ 7696],
        [ 7811],
        [ 7905

In [84]:
Xt = X.T
Xt

matrix([[2011, 2010, 2009, ..., 2008, 2009, 2010],
        [   1,    1,    1, ...,    0,    0,    0],
        [   0,    0,    0, ...,    0,    0,    0]], dtype=int64)

In [85]:
A = (Xt * X).I * Xt * Y
print(A)

[[  3.98807104]
 [-13.47591572]
 [-23.91576442]]


In [88]:
print("Les coefficients sont les suivants : \na0 = {} \na1 = {} \na2 = {} ".format( A[0,0], A[1,0], A[2,0]))

Les coefficients sont les suivants : 
a0 = 3.98807104335788 
a1 = -13.475915722747445 
a2 = -23.9157644168927 
